# Generated by Django 4.2.2 on 2023-07-06 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='purchaised_by',
        ),
    ]
