# Generated by Django 4.2.2 on 2023-07-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('aproved', 'APROVED'), ('rejected', 'REJECTED')], max_length=200, null=True),
        ),
    ]
