# Generated by Django 4.2.2 on 2023-07-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_book_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktransaction',
            name='status',
            field=models.CharField(choices=[('returned', 'RETURNED'), ('rented', 'RENTED')], max_length=20),
        ),
    ]
