# Generated by Django 4.2.2 on 2023-07-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_booktransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('aproved', 'APROVED'), ('pending', 'PENDING'), ('rejected', 'REJECTED')], max_length=200, null=True),
        ),
    ]
