# Generated by Django 4.2.2 on 2023-07-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aproval',
        ),
    ]
