# Generated by Django 4.2.2 on 2023-07-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_aproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('member', 'MEMBER'), ('librarian', 'LIBRARIAN')], default='member', max_length=250),
        ),
    ]
